### ISSUE TITLE
ofs_parse: ast.get_source_segment() unavailable

### ISSUE THREAD

**Issue by chipb** [OPAE/opae-libs#143]
The `get_source_segment()` used at https://github.com/OPAE/opae-libs/blob/b75690cf62b9d2fc4a0d50d1e424c0ce00d790ea/scripts/ofs_parse.py#L222 was not added to the `ast` module until Python 3.8, so this header generation script does not currently execute for the minimum Python 3.6 checked by CMakeLists.txt and provided with EL7.

**Comment by chipb** [comment]
[I spoke too soon.](https://github.com/OPAE/opae-libs/pull/145#issuecomment-800742867)

That PR will indeed make it no longer crash, but it's generating some bogus output characters. Python 3.6 and 3.7 are not providing the end column for many `ast.Node`s, and I think trying to reason about the end boundary while working with the raw input strings will only lead to tears for us. It's probably unsalvageable in its current form, so I'll probably end up reverting it tomorrow if nothing comes to mind.

Rodrigo has made that component optional, so at least it should build without that tool on older Python environments until there's a better solution.

**Comment by r-rojo** [comment]
Closing as this was fixed by refactoring to not rely on get_source_segment.
